# Storage mode (files only)
storage_mode = "files"

# Path to the directory where notes will be stored.
# Supports ~ or $HOME.
path_to_main_vault = "$HOME/terminal-note"

# Path to the directory where imline notes will be stored. 
# Supports ~ or $HOME.
path_to_inline_note = "$HOME/terminal-note/cli_note"

# File extension for notes: txt, md
file_extension = ".md"

# Path to the template file.
# Supports ~ or $HOME.
path_to_template_note = "$HOME/terminal-note/Templates/base.md"

# Editor to write notes comfortably: vi, vim, nvim, micro, nano, etc.
editor = "hx"
